"use client";
import { useEffect, useState } from "react";
import type { SymbolPayload } from "@/lib/alpaca";
const ranges = ["1D", "5D", "10D", "30D", "6M", "1Y"];
export function SymbolWorkspace({ symbol }: { symbol: string }) {
  const [range, setRange] = useState("1D");
  const [data, setData] = useState<SymbolPayload | null>(null);
  useEffect(() => { setData(null); fetch(`/api/symbol/${symbol}?range=${range}`).then(r => r.json()).then(setData); }, [symbol, range]);
  const bars = data?.bars ?? []; const values = bars.map(x => x.c);
  const lo = Math.min(...values), hi = Math.max(...values), pad = (hi - lo || 1) * .08;
  const path = values.map((v, i) => `${i ? "L" : "M"}${i / Math.max(values.length - 1, 1) * 100},${90 - (v - (lo - pad)) / ((hi - lo) + pad * 2) * 75}`).join(" ");
  const up = (data?.change ?? 0) >= 0, percent = data?.changePercent;
  return <main className="symbol-page"><a className="back-link" href="/">← Back to news</a><header className="symbol-title"><div><p className="kicker">Equity research</p><h1>{symbol}</h1></div><strong className={up ? "positive" : "negative"}>{data?.price ? `$${data.price.toFixed(2)}` : "—"}<small>{percent == null ? "Loading quote…" : `${up ? "+" : ""}${percent.toFixed(2)}% today`}</small></strong></header><section className="symbol-chart detailed"><div className="chart-label"><strong>{range === "1D" ? "Today" : range} price action</strong><span>Alpaca IEX</span></div>{!data ? <div className="chart-loading"><i/><span>Loading chart data</span></div> : <><div className="chart-axis"><span>${(hi + pad).toFixed(2)}</span><span>${((hi + lo) / 2).toFixed(2)}</span><span>${(lo - pad).toFixed(2)}</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d={path}/></svg><div className="chart-dates"><span>{bars[0]?.t ? new Date(bars[0].t).toLocaleDateString() : ""}</span><span>{bars.at(-1)?.t ? new Date(bars.at(-1)!.t).toLocaleDateString() : ""}</span></div></>}<nav className="chart-ranges">{ranges.map(item => <button key={item} className={range === item ? "active" : ""} onClick={() => setRange(item)}>{item}</button>)}</nav></section><section className="symbol-metrics"><div><span>Previous close</span><strong>{data?.price ? `$${(data.price - (data.change ?? 0)).toFixed(2)}` : "—"}</strong></div><div><span>Day change</span><strong className={up ? "positive" : "negative"}>{data?.change == null ? "—" : `${up ? "+" : ""}$${data.change.toFixed(2)}`}</strong></div><div><span>Chart range</span><strong>{lo === Infinity ? "—" : `$${lo.toFixed(2)} – $${hi.toFixed(2)}`}</strong></div></section><section className="symbol-news"><p className="kicker">Related coverage</p><h2>{symbol} news</h2>{data?.articles.map(a => <a key={a.id} href={a.url} target="_blank" rel="noreferrer"><strong>{a.headline}</strong><span>{a.source}</span></a>)}</section></main>;
}
