"use client";
import { useEffect, useState } from "react";
import type { SymbolPayload } from "@/lib/alpaca";
const ranges = ["1D", "5D", "10D", "30D", "6M", "1Y"];
const money=(value:number|null|undefined)=>value==null?"—":`$${value.toLocaleString(undefined,{maximumFractionDigits:2})}`;
const count=(value:number|null|undefined)=>value==null?"—":value.toLocaleString();
export function SymbolWorkspace({ symbol }: { symbol: string }) {
 const [range,setRange]=useState("1D"),[data,setData]=useState<SymbolPayload|null>(null);
 useEffect(()=>{setData(null);fetch(`/api/symbol/${symbol}?range=${range}`).then(r=>r.json()).then(setData)},[symbol,range]);
 const bars=data?.bars??[],v=bars.map(x=>x.c),lo=Math.min(...v),hi=Math.max(...v),pad=(hi-lo||1)*.08,up=(data?.change??0)>=0;
 const path=v.map((x,i)=>`${i?"L":"M"}${i/Math.max(v.length-1,1)*100},${90-(x-(lo-pad))/((hi-lo)+2*pad)*75}`).join(" ");
 const stats=[["Previous close",money(data?.metrics.previousClose)],["Open",money(data?.metrics.open)],["Day’s range",`${money(data?.metrics.low)} – ${money(data?.metrics.high)}`],["Volume",count(data?.metrics.volume)],["Last price",money(data?.price)],["Chart range",lo===Infinity?"—":`${money(lo)} – ${money(hi)}`]];
 return <main className="symbol-page yf-detail"><a className="back-link" href="/">← Back to news</a><header className="symbol-hero"><div><p className="exchange-label">NASDAQGS · IEX market data · USD</p><h1>{symbol}<button aria-label={`Add ${symbol} to watchlist`}>☆</button></h1></div><div className={up?"positive":"negative"}><strong>{money(data?.price)}</strong><b>{data?.change==null?"Loading…":`${up?"+":""}${money(data.change)} (${up?"+":""}${data.changePercent?.toFixed(2)}%)`}</b><small>Regular session</small></div></header><section className="symbol-chart detailed"><div className="chart-toolbar"><span>Price chart</span><button>⌁ Chart settings</button></div><div className="chart-label"><strong>{range === "1D" ? "Today’s price action" : `${range} price action`}</strong><span>Alpaca IEX</span></div>{!data?<div className="chart-loading"><i/><span>Loading chart data</span></div>:<><div className="chart-axis"><span>{money(hi+pad)}</span><span>{money((hi+lo)/2)}</span><span>{money(lo-pad)}</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d={path}/></svg><div className="chart-dates"><span>{bars[0]?.t?new Date(bars[0].t).toLocaleString([],{month:"short",day:"numeric",hour:"numeric"}):""}</span><span>{bars.at(-1)?.t?new Date(bars.at(-1)!.t).toLocaleString([],{month:"short",day:"numeric",hour:"numeric"}):""}</span></div></>}<nav className="chart-ranges">{ranges.map(item=><button key={item} className={range===item?"active":""} onClick={()=>setRange(item)}>{item}</button>)}</nav></section><section className="pulse-card"><p className="kicker">What’s happening with {symbol}?</p><p>{data?.change==null?"Loading today’s market context…":`${symbol} is ${up?"up":"down"} ${Math.abs(data.changePercent??0).toFixed(2)}% for the session. Explore the price action, session statistics, and latest related coverage below.`}</p><div><button>Price action</button><button>Related news</button><button>Market context</button></div></section><section className="metrics-grid">{stats.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><details className="company-overview"><summary>{symbol} overview</summary><p>Company description, sector classification, earnings calendar, valuation, and analyst-estimate coverage will be added when a fundamentals provider is connected.</p></details><section className="symbol-news"><div className="news-heading"><div><p className="kicker">Recent news</p><h2>{symbol} coverage</h2></div><span>{data?.articles.length??0} stories</span></div><nav className="news-tabs"><button className="active">All</button><button>News</button><button>Press releases</button></nav><div className="news-grid">{data?.articles.map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer"><strong>{a.headline}</strong><span>{a.source} · {new Date(a.updated_at).toLocaleDateString()}</span></a>)}</div></section></main>;
}
